# Generated by Django 4.1.7 on 2023-04-20 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
